project:
  type: website
  execute-dir: project
  render:
  - forecastCrashes.qmd

website:
  title: "Temporal Analysis of Road Crashes in the Australian Capital Territory"
  description: "Forecasting Road Crashes in the ACT using Time Trend and ARIMA models"
  navbar:
    left:
      - href: forecastCrashes.qmd
        text: Home
    right:
    - icon: github
      aria-label: GitHub
      href: https://github.com/Gippers
    - icon: globe
      aria-label: Personal Website
      href: https://www.thomasmartin.id.au
  sidebar:
    style: "floating"    # or "docked" / "overlay"
    pinned: true
    search: true    


format:
  html:
    fig-cap-location: top # Make sure the fig is at top, not working?
    number-sections: true
    #number-depth: 2
    colorlinks: true
    fig-pos: "H"
    theme:
      light: flatly
      dark: darkly
    toggle: true
    #css: styles.css
    grid: 
      body-width: 1000px
      margin-width: 200px 
    toc: true
    toc-location: left # TOC on the left
    #code-fold: true
    #code-tools: true

editor: 
  markdown: 
    wrap: 72
engine: knitr  

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

bibliography: actCrashes.bib
csl: csl/harvard-cite-them-right.csl